# Configuration for Git Auto Pull Service
check_interval: 60  # Check every 1 minutes (in seconds)

repositories:
  - path: "/home/username/repo1"
    branch: "master"
  # add more repositories
  # - path: "/path/to/repo2"
  #   branch: "main"
