# Configuration for Git Auto Pull Service
check_interval: 60  # Check every 1 minutes (in seconds)

repositories:
  - path: "/home/username/repo1"
    branch: "master"
    type: "nextjs"  # Add type for NextJS repos
    pm2_ids: [1, 2]  # PM2 process IDs to manage
    build_command: "npm run build"  # Build command to run
  # add more repositories
  # - path: "/path/to/repo2"
  #   branch: "main"
  #   type: "standard"  # Standard repo without build
